git-hometask/katsiaryna-lapitskaya/BOOTCAMP.md

added some info about me

---

git-hometask/andrei-tarassov/BOOTCAMP.md

I create a Pull Request in GitHub from my branch to `main` branch

My version1

---

git-hometask/Krzysztof-Nalewajek/BOOTCAMP.md

Krzysztof Nalewajek home task

---

git-hometask/tetiana-zalata/BOOTCAMP.md

pr from `tetiana-zalata` branch to `main` branch

Tetiana Zalata HT

---

git-hometask/adam-tarczewski/BOOTCAMP.md

Here is the hometask, that was assigned. Have a nice day.

hometask from adam tarczewski

---

git-hometask/olegs-matvejevs/BOOTCAMP.md

Olegs matvejevs

---

git-hometask/mateusz-pichniarczyk/BOOTCAMP.md

Mateusz Pichniarczyk home task

---

git-hometask/marek-pownuk/BOOTCAMP.md

Marek Pownuk git home task

---

git-hometask/piotr-zdebski/BOOTCAMP.md

update on BOOTCAMP.md

---

git-hometask/hanna-beier/BOOTCAMP.md

Hanna Beier Git home task

---

git-hometask/lera-nong/BOOTCAMP.md

lera-nong-hometask

---

git-hometask/paulina-lutarewicz/BOOTCAMP.md

Paulina Lutarewicz homework

---

git-hometask/andrii-karlov/BOOTCAMP.md

Andrii Karlov (akarlov@evolution.com) hometask

Andrii karlov

---

git-hometask/ruslan-slepuhin/BOOTCAMP.md

Hello Andrejs!
All homework items are done!
Ruslan Slepuhin

Ruslan slepuhin

---

git-hometask/paulina-luczynska/BOOTCAMP.md

Paulina luczynska

---

git-hometask/inga-muitiniece/BOOTCAMP.md

Inga Muitiniece hometask_1

---

git-hometask/tatsiana-tsishkevich/BOOTCAMP.md

Tatsiana Tsishkevich

---

git-hometask/sergejs-suslovs/BOOTCAMP.md

sergejs-suslovs

---

git-hometask/islom-ismoilov/BOOTCAMP.md

Added BOOTCAMP.md in Islom Ismoilov folder

Add BOOTCAMP.md in Islom Ismoilov folder

---

git-hometask/oskar-niewiadomy/BOOTCAMP.md

Commit of the homework
